/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Details extends javax.swing.JFrame {
 Connection conn = null;
ResultSet rs=null;
Statement st=null;
 String u1;   
    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }
    
    public Details(String user)
    {
         initComponents();

         u1=user;
        
     
 try{
    
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
       
String sql1="select * from resume where username="+"'"+u1+"'";
String sql2="select * from skills where username="+"'"+u1+"'";
String sql3="select * from interests where username="+"'"+u1+"'";
String sql4="select * from languages where username="+"'"+u1+"'";
String sql5="select * from applicant where username="+"'"+u1+"'";
String sql6="select * from experiences where username="+"'"+u1+"'";
String sql8="select * from  projects where username="+"'"+u1+"'";
String sql7="select * from  phone_nos where username="+"'"+u1+"'";


     try
     {
         
         rs=st.executeQuery(sql1);
    
       if(rs.next()){
           jLabel23.setText(rs.getString("Fname"));
           jLabel24.setText(rs.getString("Lname"));
           address.setText(rs.getString("Address"));
           education.setText(rs.getString("Qualification"));
            }
                            
      }
       
   catch(Exception e)
   {
       e.printStackTrace();
   }
     try{
rs=st.executeQuery(sql2);
if(rs.next()){
    ski.setText(rs.getString("skill"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }
       try{
rs=st.executeQuery(sql3);
if(rs.next()){
    interest.setText(rs.getString("interest"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }

         try{
rs=st.executeQuery(sql4);
if(rs.next()){
    language.setText(rs.getString("language"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }

           try{
rs=st.executeQuery(sql6);
if(rs.next()){
    experience.setText(rs.getString("experience"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }

    
  try{
rs=st.executeQuery(sql5);
if(rs.next()){
    dob.setText(rs.getString("DOB"));
    age.setText(rs.getString("age"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }
  try{
      
rs=st.executeQuery(sql8);
if(rs.next()){
    pro.setText(rs.getString("project"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }
  try{
rs=st.executeQuery(sql7);
if(rs.next()){
    phno.setText(rs.getString("phone_no"));
}
     }
    catch(Exception e)
            {
            e.printStackTrace();
            }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        phno = new javax.swing.JLabel();
        experience = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        education = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        ski = new javax.swing.JLabel();
        language = new javax.swing.JLabel();
        interest = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("User Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("First name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel5.setText("Education");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel7.setText("Skills");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel6.setText("Experience");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 60, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel9.setText("DOB");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel10.setText("Phone no:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel12.setText("Interests");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel13.setText("Languages");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 120, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel14.setText("Projects");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 100, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        dob.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 180, 20));

        age.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 150, 40));

        phno.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 230, 30));

        experience.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 140, 30));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 180, 30));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 160, 30));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("SEARCH JOBS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 290, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("DELETE DETAILS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 290, -1));

        education.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(education, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 140, 20));

        address.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 510, 40));

        ski.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(ski, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 170, 40));

        language.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(language, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 210, 30));

        interest.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(interest, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 390, 30));

        pro.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 160, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("EDIT ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 300, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try
{
PreparedStatement stmt1=conn.prepareStatement("delete from skills where username=?");  
stmt1.setString(1,u1);  
stmt1.executeUpdate();
PreparedStatement stmt2=conn.prepareStatement("delete from interests where username=?");  
stmt2.setString(1,u1);  
stmt2.executeUpdate();
PreparedStatement stmt5=conn.prepareStatement("delete from search where username=?");  
stmt5.setString(1,u1);  
stmt5.executeUpdate();
PreparedStatement stmt6=conn.prepareStatement("delete from checks where username=?");  
stmt6.setString(1,u1);  
stmt6.executeUpdate();
PreparedStatement stmt7=conn.prepareStatement("delete from result where username=?");  
stmt7.setString(1,u1);  
stmt7.executeUpdate();
PreparedStatement stmt8=conn.prepareStatement("delete from languages where username=?");  
stmt8.setString(1,u1);  
stmt8.executeUpdate();
PreparedStatement stmt9=conn.prepareStatement("delete from projects where username=?");  
stmt9.setString(1,u1);  
stmt9.executeUpdate();
PreparedStatement stmt=conn.prepareStatement("delete from experiences where username=?");  
stmt.setString(1,u1);  
stmt.executeUpdate();
PreparedStatement stmt10=conn.prepareStatement("delete from phone_nos where username=?");  
stmt10.setString(1,u1);  
stmt10.executeUpdate();
PreparedStatement stmt3=conn.prepareStatement("delete from resume where username=?");  
stmt3.setString(1,u1);  
stmt3.executeUpdate();
PreparedStatement stmt4=conn.prepareStatement("delete from applicant where username=?");  
stmt4.setString(1,u1);  
stmt4.executeUpdate();
}
catch(Exception e)
{
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Searchjob sj=new Searchjob();
sj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Editacc ec=new Editacc(u1);
ec.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel education;
    private javax.swing.JLabel experience;
    private javax.swing.JLabel interest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel language;
    private javax.swing.JLabel phno;
    private javax.swing.JLabel pro;
    private javax.swing.JLabel ski;
    // End of variables declaration//GEN-END:variables
}
