/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class editdetails extends javax.swing.JFrame {

    /**
     * Creates new form editdetails
     */
    String e4,p4,c4,l4;
    int ei4;
    Connection conn=null;
    ResultSet rs=null;
    Statement st=null;
    private PreparedStatement pt2=null;
    public editdetails() {
        initComponents();
    }
    int e6;
     public editdetails(int e5) {
        initComponents();
        try{
    e6=e5;
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  //System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ename3 = new javax.swing.JRadioButton();
        company3 = new javax.swing.JRadioButton();
        position3 = new javax.swing.JRadioButton();
        location3 = new javax.swing.JRadioButton();
        ename4 = new javax.swing.JTextField();
        position4 = new javax.swing.JTextField();
        location4 = new javax.swing.JTextField();
        comapany4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ename3.setBackground(new java.awt.Color(255, 204, 204));
        ename3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        ename3.setText("NAME");
        ename3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename3ActionPerformed(evt);
            }
        });
        getContentPane().add(ename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 301, -1, -1));

        company3.setBackground(new java.awt.Color(255, 204, 204));
        company3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        company3.setText("COMPANY");
        company3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company3ActionPerformed(evt);
            }
        });
        getContentPane().add(company3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 380, -1, -1));

        position3.setBackground(new java.awt.Color(255, 204, 204));
        position3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        position3.setText("POSITION");
        position3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position3ActionPerformed(evt);
            }
        });
        getContentPane().add(position3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 454, -1, -1));

        location3.setBackground(new java.awt.Color(255, 204, 204));
        location3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        location3.setText("LOCATION");
        location3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location3ActionPerformed(evt);
            }
        });
        getContentPane().add(location3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 531, -1, -1));
        getContentPane().add(ename4, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 311, 154, -1));
        getContentPane().add(position4, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 454, 154, -1));
        getContentPane().add(location4, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 531, 154, -1));

        comapany4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comapany4ActionPerformed(evt);
            }
        });
        getContentPane().add(comapany4, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 390, 154, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setText("After you type in the new detail click the radio button..");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 164, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ename3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename3ActionPerformed
        try {
            // TODO add your handling code here:
            
            e4=ename4.getText();
            pt2=conn.prepareStatement("update employer set ename=? where e_id=?");
            pt2.setString(1,e4);
            pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_ename3ActionPerformed

    private void company3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company3ActionPerformed
        try {
            // TODO add your handling code here:
            
            c4=comapany4.getText();
            pt2=conn.prepareStatement("update employer set company=? where e_id=?");
            pt2.setString(1,c4);
            pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_company3ActionPerformed

    private void position3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position3ActionPerformed
        try {
            // TODO add your handling code here:
            
            p4=position4.getText();
            pt2=conn.prepareStatement("update employer set position=? where e_id=?");
            pt2.setString(1,p4);
            pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_position3ActionPerformed

    private void location3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location3ActionPerformed
        try {
            // TODO add your handling code here:
            
            l4=location4.getText();
            pt2=conn.prepareStatement("update employer set loaction=? where e_id=?");
            pt2.setString(1,l4);
            pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_location3ActionPerformed

    private void comapany4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comapany4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comapany4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comapany4;
    private javax.swing.JRadioButton company3;
    private javax.swing.JRadioButton ename3;
    private javax.swing.JTextField ename4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton location3;
    private javax.swing.JTextField location4;
    private javax.swing.JRadioButton position3;
    private javax.swing.JTextField position4;
    // End of variables declaration//GEN-END:variables
}
