/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class employerdetailssignin extends javax.swing.JFrame {

    /**
     * Creates new form employerdetailssignin
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    private PreparedStatement pt;
    public employerdetailssignin() {
        initComponents();
    }
    String e1;
    int e_id6;
     public employerdetailssignin(String ename3 ) {
        initComponents();
        e1=ename3;
        try{
    
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  //System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
        String sql1="select * from employer where ename="+"'"+e1+"'";
          try
     {
         
         rs=st.executeQuery(sql1);
    
       if(rs.next()){
           ename2.setText(rs.getString("ename"));
           company2.setText(rs.getString("company"));
           location2.setText(rs.getString("location"));
           position2.setText(rs.getString("position"));
           e_id6=Integer.parseInt(rs.getString(1));
           e_id2.setText(rs.getString(1));
            }
                            
      }
       
   catch(Exception e)
   {
       e.printStackTrace();
   }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        e_id2 = new javax.swing.JLabel();
        position2 = new javax.swing.JLabel();
        post = new javax.swing.JButton();
        searchapplicants = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        company2 = new javax.swing.JLabel();
        ename2 = new javax.swing.JLabel();
        location2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 177, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("E_ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 289, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("PROFILE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 92, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setText("POSITION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 509, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setText("COMPANY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 406, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel6.setText("LOCATION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 616, -1, -1));

        edit.setBackground(new java.awt.Color(153, 255, 255));
        edit.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 119, -1, -1));

        delete.setBackground(new java.awt.Color(153, 255, 255));
        delete.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        delete.setText("DELETE ACCOUNT");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 192, -1, -1));

        e_id2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        getContentPane().add(e_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 289, 170, 30));

        position2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        getContentPane().add(position2, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 509, 220, 30));

        post.setBackground(new java.awt.Color(153, 255, 255));
        post.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        post.setText("POST JOBS");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 268, -1, -1));

        searchapplicants.setBackground(new java.awt.Color(153, 255, 255));
        searchapplicants.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        searchapplicants.setText("SEARCH APPLICANTS");
        searchapplicants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchapplicantsActionPerformed(evt);
            }
        });
        getContentPane().add(searchapplicants, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 345, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        company2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N

        ename2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N

        location2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(788, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(company2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(location2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ename2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(376, 376, 376))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(ename2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(company2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(location2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        new editdetails(e_id6).setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            // TODO add your handling code here:
            
            PreparedStatement pt=conn.prepareStatement("delete from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailssignin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_deleteActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
        new postjobs(e_id6).setVisible(true);
    }//GEN-LAST:event_postActionPerformed

    private void searchapplicantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchapplicantsActionPerformed
        // TODO add your handling code here:
        new searchapplicants().setVisible(true);
    }//GEN-LAST:event_searchapplicantsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employerdetailssignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employerdetailssignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employerdetailssignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employerdetailssignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employerdetailssignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel company2;
    private javax.swing.JButton delete;
    private javax.swing.JLabel e_id2;
    private javax.swing.JButton edit;
    private javax.swing.JLabel ename2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel location2;
    private javax.swing.JLabel position2;
    private javax.swing.JButton post;
    private javax.swing.JButton searchapplicants;
    // End of variables declaration//GEN-END:variables
}
