/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class Searchjob extends javax.swing.JFrame {

    /**
     * Creates new form Searchjob
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    CallableStatement stmt=null;
    public Searchjob() {
        initComponents();
        try{
    
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  //System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ed2 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        e2 = new javax.swing.JRadioButton();
        l2 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        l1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        ed1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Search Filters");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        ed2.setBackground(new java.awt.Color(255, 255, 153));
        ed2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        ed2.setText("Education");
        ed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed2ActionPerformed(evt);
            }
        });
        getContentPane().add(ed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        c2.setBackground(new java.awt.Color(255, 255, 153));
        c2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        c2.setText("Company");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        e2.setBackground(new java.awt.Color(255, 255, 153));
        e2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        e2.setText("Experience");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        l2.setBackground(new java.awt.Color(255, 255, 153));
        l2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        l2.setText("Location");
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Suggested Jobs:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 190, 30));

        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 190, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 202, 150, 20));

        ed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed1ActionPerformed(evt);
            }
        });
        getContentPane().add(ed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 190, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 432, 810, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setText("Open positions");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 180, -1));
        getContentPane().add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 100, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        try {
            // TODO add your handling code here:
            String l3=l1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where location=?");
            
            ps.setString(1,l3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_l2ActionPerformed

    private void ed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed2ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String ed3=ed1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where qualification=?");
            
            ps.setString(1,ed3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ed2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
         /*try {
            // TODO add your handling code here:
            String l3=c1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where location=?");
            
            ps.setString(1,l3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_c1ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int e3=Integer.parseInt(e1.getText());
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where experience=?");
            
            ps.setInt(1,e3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_e2ActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
       /*  try {
            // TODO add your handling code here:
            String l3=l1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where location=?");
            
            ps.setString(1,l3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_l1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String c3=c1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from locationview where company_name=?");
            
            ps.setString(1,c3);
            rs=ps.executeQuery();
            
            
             table.setModel(DbUtils.resultSetToTableModel(rs));
             stmt=conn.prepareCall("{?= call totaljobs(?)}");  
stmt.setString(2,c3);    
stmt.registerOutParameter(1,Types.INTEGER);  
stmt.execute();  
v1.setText(String.valueOf(stmt.getInt(1)));  
          
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void ed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ed1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchjob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JTextField e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JTextField ed1;
    private javax.swing.JRadioButton ed2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField l1;
    private javax.swing.JRadioButton l2;
    private javax.swing.JTable table;
    private javax.swing.JLabel v1;
    // End of variables declaration//GEN-END:variables
}
