/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class searchapplicants extends javax.swing.JFrame {

    /**
     * Creates new form searchapplicants
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    public searchapplicants() {
        initComponents();
        try{
    
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  //System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q2 = new javax.swing.JRadioButton();
        e2 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        l2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        s1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        a1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        q2.setBackground(new java.awt.Color(255, 204, 204));
        q2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        q2.setText("QUALIFICATION");
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 206, 47));

        e2.setBackground(new java.awt.Color(255, 204, 204));
        e2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        e2.setText("EXPERIENCE");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 184, -1, 40));

        s2.setBackground(new java.awt.Color(255, 204, 204));
        s2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        s2.setText("SKILLS");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 242, 173, -1));

        l2.setBackground(new java.awt.Color(255, 204, 204));
        l2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        l2.setText("LANGUAGE");
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 313, 173, 47));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 432, 878, 195));

        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 245, 138, 37));

        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 138, 33));
        getContentPane().add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 138, 36));

        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 313, 138, 36));

        a1.setBackground(new java.awt.Color(255, 204, 204));
        a1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("AVAILABLE CANDIDATES");
        a1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, 29));
        a1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 110, 130, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setText("GRADE");
        a1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, -1));

        g1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        a1.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, 210, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("SEARCH FILTERS");
        a1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 215, -1));

        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String s3=s1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from applicantview where skill=?");
            
            ps.setString(1,s3);
            rs=ps.executeQuery();
            
            
             table2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String l3=l1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from applicantview2 where language=?");
            
            ps.setString(1,l3);
            rs=ps.executeQuery();
            
            
             table2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_l2ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String e3=e1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from applicantview1 where experience=?");
            
            ps.setString(1,e3);
            rs=ps.executeQuery();
            
            
             table2.setModel(DbUtils.resultSetToTableModel(rs));
                CallableStatement stmt=conn.prepareCall("{call grading(?)}");      
stmt.registerOutParameter(1,Types.VARCHAR);  
stmt.execute();  
g1.setText(stmt.getString(1));

          } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_e2ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String q3=q1.getText();
            PreparedStatement ps;
            
            ps = conn.prepareStatement("select * from applicantview3 where qualification=?");
            
            ps.setString(1,q3);
            rs=ps.executeQuery();
            
            
             table2.setModel(DbUtils.resultSetToTableModel(rs));
             CallableStatement stmt=conn.prepareCall("{?= call expqual(?)}");  
stmt.setString(2,q3);    
stmt.registerOutParameter(1,Types.INTEGER);  
stmt.execute();  
a2.setText(String.valueOf(stmt.getInt(1)));
        } catch (SQLException ex) {
            Logger.getLogger(Searchjob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q2ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchapplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchapplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchapplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchapplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchapplicants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JTextField e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l1;
    private javax.swing.JRadioButton l2;
    private javax.swing.JTextField q1;
    private javax.swing.JRadioButton q2;
    private javax.swing.JTextField s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
