/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class Signupapplicant extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs=null;
Statement st=null;
 // jFrame.setBackground(Color.RED);
    /**
     * Creates new form Signupapplicant
     */
    public Signupapplicant() {
        initComponents();
         
        
     
 try{
    
  String driverName = "oracle.jdbc.driver.OracleDriver";
  Class.forName(driverName);
  String serverName = "LAPTOP-9GA03MGL";
  String serverPort = "1521";
  String sid = "XE";
  String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":"+sid;
  String username = "sys"; 
  String password = "*****"; 
  conn = DriverManager.getConnection(url,username,password);
  st=conn.createStatement();
  //System.out.println("Success");
 } catch (ClassNotFoundException e){
  System.out.println("Cant find db server" + e.getMessage());
 } catch (SQLException e) {
  System.out.println("Cant connect" + e.getMessage());
 }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        ski = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        lang = new javax.swing.JTextField();
        proj = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        edu = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        pword = new javax.swing.JPasswordField();
        inte = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        comp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        aid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1380, 800));
        setSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setText("SIGNUP FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Enter the following details:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel4.setText("Last name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel6.setText("Project");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel7.setText("Phone no");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setText("Skills");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 50, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel9.setText("DOB");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 60, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel10.setText("Education");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel11.setText("Interests");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel12.setText("Experience");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel13.setText("Languages");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 100, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox1.setText("I agree to the terms and conditions");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 830, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel14.setText("Password");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel15.setText("Username");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 90, -1));

        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 140, -1));

        ski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skiActionPerformed(evt);
            }
        });
        getContentPane().add(ski, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 140, -1));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 140, -1));

        lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langActionPerformed(evt);
            }
        });
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 140, -1));

        proj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projActionPerformed(evt);
            }
        });
        getContentPane().add(proj, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 140, -1));
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 140, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 140, -1));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 140, -1));
        getContentPane().add(edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 140, -1));

        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        getContentPane().add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 140, -1));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 140, -1));
        getContentPane().add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 140, -1));

        inte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteActionPerformed(evt);
            }
        });
        getContentPane().add(inte, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 140, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 880, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel16.setText("Company");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, -1));
        getContentPane().add(comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 130, -1));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel17.setText("Aid");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 760, 50, -1));

        aid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidActionPerformed(evt);
            }
        });
        getContentPane().add(aid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 770, 140, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 930));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projActionPerformed

    private void langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s1=fname.getText();
String s2=lname.getText();
String s3=add.getText();
String s4=uname.getText();
String s5=pword.getText();
String s6=inte.getText();
String s7=ski.getText();
String s8=exp.getText();
String s9=ph.getText();
String s10=DOB.getText();
String s11=lang.getText();
String s12=edu.getText();
String s13=proj.getText();
String s14=comp.getText();
String id=aid.getText();
try{

PreparedStatement stmt1=conn.prepareStatement("insert into applicant(username,dob,password) values(?,?,?)");  
stmt1.setString(1,s4);
stmt1.setString(2,s10);
stmt1.setString(3,s5);
stmt1.executeUpdate();

PreparedStatement stmt6=conn.prepareStatement("insert into resume(a_id,username,fname,lname,qualification,address) values(?,?,?,?,?,?)");  
stmt6.setString(1,id);
stmt6.setString(2,s4);
stmt6.setString(3,s1);
stmt6.setString(4,s2);
stmt6.setString(5,s12);
stmt6.setString(6,s3);
stmt6.executeUpdate();

PreparedStatement stmt2=conn.prepareStatement("insert into skills values(?,?,?)");  
stmt2.setString(1,id);
stmt2.setString(2,s4);
stmt2.setString(3,s7);
stmt2.executeUpdate();

PreparedStatement stmt10=conn.prepareStatement("insert into projects values(?,?,?)");  
stmt10.setString(1,id);
stmt10.setString(2,s4);
stmt10.setString(3,s13);
stmt10.executeUpdate();


PreparedStatement stmt4=conn.prepareStatement("insert into interests values(?,?,?)");  
stmt4.setString(1,id);
stmt4.setString(2,s4);
stmt4.setString(3,s6);
stmt4.executeUpdate();

PreparedStatement stmt5=conn.prepareStatement("insert into phone_nos values(?,?,?)");  
stmt5.setString(1,id);
stmt5.setString(2,s4);
stmt5.setString(3,s9);
stmt5.executeUpdate();

PreparedStatement stmt7=conn.prepareStatement("insert into languages values(?,?,?)");  
stmt7.setString(1,id);
stmt7.setString(2,s4);
stmt7.setString(3,s11);
stmt7.executeUpdate();

PreparedStatement stmt11=conn.prepareStatement("insert into experiences(a_id,username,ecompany,experience) values(?,?,?,?)");  
stmt11.setString(1,id);
stmt11.setString(2,s4);
stmt11.setString(3,s14);
stmt11.setString(4,s8);
stmt11.executeUpdate();
}
catch(Exception e)
{
    
}
Details newd=new Details(s4);
newd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phActionPerformed

    private void inteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inteActionPerformed

    private void skiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skiActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void aidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aidActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signupapplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signupapplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signupapplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signupapplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signupapplicant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField add;
    private javax.swing.JTextField aid;
    private javax.swing.JTextField comp;
    private javax.swing.JTextField edu;
    private javax.swing.JTextField exp;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField inte;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lang;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField proj;
    private javax.swing.JPasswordField pword;
    private javax.swing.JTextField ski;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
