/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobportal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author harshsree
 */
public class editdetails extends javax.swing.JFrame {

    /**
     * Creates new form editdetails
     */
    String e4,p4,c4,l4;
    int ei4;
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    private PreparedStatement pt2=null;
    public editdetails() {
        initComponents();
    }
    int e6;
    public editdetails(int e5)
    {
        e6=e5;
             initComponents();
               try
    {
            String driverName="oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName="Harshsree";
            String serverPort="1521";
            String sid="XE";
            String url="jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username="system";
            String password="sreenidhi1";
            conn=DriverManager.getConnection(url,username,password);
             Statement st = conn.createStatement();
        }
        
        catch (ClassNotFoundException e)
        {
            System.out.println("couldnot find database server"+e.getMessage());
        }
        catch (SQLException e)
        {
            System.out.println("could not connect to database"+e.getMessage());
        }
       catch(Exception e)
       {
           e.printStackTrace();
       }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ename3 = new javax.swing.JRadioButton();
        comapny3 = new javax.swing.JRadioButton();
        position3 = new javax.swing.JRadioButton();
        location3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ename4 = new javax.swing.JTextField();
        company4 = new javax.swing.JTextField();
        position4 = new javax.swing.JTextField();
        location4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1680, 800));

        ename3.setText("NAME");
        ename3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename3ActionPerformed(evt);
            }
        });

        comapny3.setText("COMPANY");
        comapny3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comapny3ActionPerformed(evt);
            }
        });

        position3.setText("POSITION");
        position3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position3ActionPerformed(evt);
            }
        });

        location3.setText("LOCATION");
        location3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location3ActionPerformed(evt);
            }
        });

        jLabel1.setText("What do you want to edit??");

        location4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ename3)
                            .addComponent(comapny3)
                            .addComponent(position3)
                            .addComponent(location3))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(location4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(position4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(company4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ename4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ename3)
                    .addComponent(ename4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comapny3)
                    .addComponent(company4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position3)
                    .addComponent(position4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location3)
                    .addComponent(location4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ename3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename3ActionPerformed
        // TODO add your handling code here:
      
           try {                                      
            // TODO add your handling code here:
            e4=ename4.getText();
            pt2= conn.prepareStatement("update employer set ename=? where e_id=?");
            pt2.setString(1,e4);
             pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ename3ActionPerformed

    private void comapny3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comapny3ActionPerformed
        // TODO add your handling code here:
         
             try {                                      
            // TODO add your handling code here:
           c4=company4.getText();
           pt2= conn.prepareStatement("update employer set company=? where e_id=?");
            pt2.setString(1,c4);
             pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_comapny3ActionPerformed

    private void position3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position3ActionPerformed
        // TODO add your handling code here:
        
             try {                                      
            // TODO add your handling code here:
              p4=position4.getText();
          pt2= conn.prepareStatement("update employer set position=? where e_id=?");
            pt2.setString(1,p4);
             pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_position3ActionPerformed

    private void location3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location3ActionPerformed
        // TODO add your handling code here:
         
             try {                                      
            // TODO add your handling code here:
           l4=location4.getText();
           pt2= conn.prepareStatement("update employer set location=? where e_id=?");
            pt2.setString(1,l4);
             pt2.setInt(2,e6);
            pt2.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(editdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_location3ActionPerformed

    private void location4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_location4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton comapny3;
    private javax.swing.JTextField company4;
    private javax.swing.JRadioButton ename3;
    private javax.swing.JTextField ename4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton location3;
    private javax.swing.JTextField location4;
    private javax.swing.JRadioButton position3;
    private javax.swing.JTextField position4;
    // End of variables declaration//GEN-END:variables
}
