/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobportal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author harshsree
 */
public class employerdetailsignin extends javax.swing.JFrame {

    /**
     * Creates new form employerdetailsignin
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    private PreparedStatement pt;
    public employerdetailsignin() {
        initComponents();
    }
    String e1;
    int e_id6;
    public employerdetailsignin(String ename3)
    {
        initComponents();
        e1=ename3;
        try
    {
            String driverName="oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName="Harshsree";
            String serverPort="1521";
            String sid="XE";
            String url="jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username="system";
            String password="sreenidhi1";
            conn=DriverManager.getConnection(url,username,password);
            //System.out.println("Successfully connected to database");
            st = conn.createStatement();
            
           //  st.executeUpdate("insert into employer(e_id,ename,epassword)" +"values(e_id1,ename1,epassword1)");
        }
        
        catch (ClassNotFoundException e)
        {
            System.out.println("couldnot find database server"+e.getMessage());
        }
        catch (SQLException e)
        {
            System.out.println("could not connect to database"+e.getMessage());
        }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ename2 = new javax.swing.JTextField();
        e_id2 = new javax.swing.JTextField();
        company2 = new javax.swing.JTextField();
        position2 = new javax.swing.JTextField();
        location2 = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1680, 800));

        jLabel1.setText("NAME");

        jLabel2.setText("E_ID");

        jLabel3.setText("COMPANY");

        jLabel4.setText("POSITION");

        jLabel5.setText("LOCATION");

        ename2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename2ActionPerformed(evt);
            }
        });

        e_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_id2ActionPerformed(evt);
            }
        });

        company2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company2ActionPerformed(evt);
            }
        });

        position2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position2ActionPerformed(evt);
            }
        });

        location2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location2ActionPerformed(evt);
            }
        });

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel6.setText("PROFILE");

        delete.setText("DELETE ACCOUNT");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(21, 21, 21)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(company2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(position2)
                            .addComponent(e_id2)
                            .addComponent(ename2)
                            .addComponent(location2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(edit)
                        .addGap(49, 49, 49)
                        .addComponent(delete)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(ename2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(e_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(position2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(location2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(company2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void location2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("select * from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
                location2.setText(rs.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_location2ActionPerformed

    private void position2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("select * from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
                position2.setText(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_position2ActionPerformed

    private void company2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company2ActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("select * from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
                company2.setText(rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_company2ActionPerformed

    private void e_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_id2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("select * from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
                e_id6=Integer.parseInt(rs.getString(1));
              //  System.out.println(e_id6);
                e_id2.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_e_id2ActionPerformed

    private void ename2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename2ActionPerformed

        // TODO add your handling code here:
        ename2.setText(e1);
    }//GEN-LAST:event_ename2ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        new editdetails(e_id6).setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("delete from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employerdetailsignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employerdetailsignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employerdetailsignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employerdetailsignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employerdetailsignin().setVisible(true);
            }
        });
    }
       /*try {
            // TODO add your handling code here:
            PreparedStatement pt=conn.prepareStatement("select * from employer where ename=?");
            pt.setString(1,e1);
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
            company2.setText(rs.getString(2));
            }
                    } catch (SQLException ex) {
            Logger.getLogger(employerdetailsignin.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField company2;
    private javax.swing.JButton delete;
    private javax.swing.JTextField e_id2;
    private javax.swing.JButton edit;
    private javax.swing.JTextField ename2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField location2;
    private javax.swing.JTextField position2;
    // End of variables declaration//GEN-END:variables
}
